name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送 v* 标签时触发 (如 v1.0, v1.0.0)
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许创建 Release 和上传文件

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
      shell: cmd
    
    - name: Build Release
      run: |
        cd build
        cmake --build . --config Release --verbose
      shell: cmd
    
    - name: Prepare artifacts
      run: |
        mkdir release
        copy build\bin\Release\wasapi_capture.exe release\
        copy README.md release\
        copy README_CN.md release\
        copy docs\QUICK_START.md release\
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasapi_capture-windows-x64
        path: release/
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/wasapi_capture.exe
          release/README.md
          release/README_CN.md
          release/QUICK_START.md
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

